spring.application.name=fibonacci
spring.datasource.url=jdbc:postgresql://localhost:5432/fibonacci
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.root=INFO
server.port=8081